### ISSUE TITLE
Research the article and then the page becomes blank

### ISSUE THREAD

**Issue by siyuan-zhang** [RoiArthurB/Side-Auto_Sci-Hub#1] opened 2019-04-22 02:30 UTC
When i open a article website, and then click the auto-sci-hub. The page will becomes a blank  and Can't open the article pdf page

**Comment by RoiArthurB** [comment] 2019-04-22 04:04
Hello,

Could you send me the link you used and which browser do you use please? :)

**Comment by siyuan-zhang** [comment] 2019-04-22 12:52
Thanks for your replay.  At afternoon,  it can work again. It sound likes that the sci-hub database itself is out of order and  recovers this afternoon.

**Comment by RoiArthurB** [comment] 2019-04-23 02:41
Ok, so I'll close the issue assuming that the problem is solved (and was not depending on my plugin) ^^

**Closed as completed by RoiArthurB** 2019-04-23 02:41 UTC
